# Generated by Django 5.2.8 on 2025-11-07 15:43

import uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(verbose_name='نام فایل')),
                ('file', models.FileField(upload_to=uploader.models.get_upload_path)),
            ],
        ),
    ]
